### ISSUE TITLE
Error when running with some annotated RefSeq files (".gbff").

### ISSUE THREAD

**Issue by avilaHugo** [brinkmanlab/islandpath#13]
Dear developers, when I try to run conda version=1.0.4 on some RefSeq genomes, I get this error message:

```
...
2020/01/18 18:41:12 [GenomeUtils] Now generating required file formats (faa, ffn and ptt)

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: start [5340971] is greater than end [1335]. 
If you want to truncated and reverse complement, 
you must call trunc followed by revcom. Sorry.
STACK: Error::throw
STACK: Bio::Root::Root::throw /home/user/miniconda3/envs/IsL/lib/site_perl/5.26.2/Bio/Root/Root.pm:447
STACK: Bio::PrimarySeqI::trunc /home/user/miniconda3/envs/IsL/lib/site_perl/5.26.2/Bio/PrimarySeqI.pm:456
STACK: GenomeUtils::read_and_convert /home/user/miniconda3/envs/IsL/opt/islandpath/lib/GenomeUtils.pm:422
STACK: /home/user/miniconda3/envs/IsL/bin/islandpath:129
-----------------------------------------------------------
```

**Comment by innovate-invent** [comment]
Hi, thanks for your interest in IslandPath.
This is a known issue with genes crossing the origin.
Please see https://github.com/brinkmanlab/islandpath/issues/2#issuecomment-370946485 for more information.

**Comment by avilaHugo** [comment]
Hi thank you for the answer.

**Comment by innovate-invent** [comment]
@avilaHugo Your comment in the other thread pointed out a patch that fixes this issue.
That patch should be present in the version of islandpath installed via conda.
Is this not the case?

**Comment by avilaHugo** [comment]
Hi, i tried to replicate my installation in another env and this time it worked. I don't why the other times it didin't . Meybe i didn't define the program version in the conda installation. Like this:

`conda install -c bioconda islandpath=1.0.4`

Sorry for the trouble.

**Comment by innovate-invent** [comment]
No worries. Thanks for looking into it.
