### ISSUE TITLE
Can't locate Bio/Perl.pm in @INC (you may need to install the Bio::Perl module)

### ISSUE THREAD

**Issue by gucedac** [brinkmanlab/islandpath#17]
Hi, I tried to use islandpath but I had a problem with the installation.
I already installed BioPerl, however, when I execute the program apper this error:

`Can't locate Bio/Perl.pm in @INC (you may need to install the Bio::Perl module) (@INC contains: /media/guillermo/Work/miniconda3/envs/islandpath/opt/islandpath/lib /home/guillermo/perl5/lib/perl5 /media/guillermo/Work/miniconda3/envs/islandpath/lib/perl5/5.32/site_perl /media/guillermo/Work/miniconda3/envs/islandpath/lib/perl5/site_perl /media/guillermo/Work/miniconda3/envs/islandpath/lib/perl5/5.32/vendor_perl /media/guillermo/Work/miniconda3/envs/islandpath/lib/perl5/vendor_perl /media/guillermo/Work/miniconda3/envs/islandpath/lib/perl5/5.32/core_perl /media/guillermo/Work/miniconda3/envs/islandpath/lib/perl5/core_perl .) at /media/guillermo/Work/miniconda3/envs/islandpath/opt/islandpath/lib/GenomeUtils.pm line 52.
BEGIN failed--compilation aborted at /media/guillermo/Work/miniconda3/envs/islandpath/opt/islandpath/lib/GenomeUtils.pm line 52.
Compilation failed in require at /media/guillermo/Work/miniconda3/envs/islandpath/bin/islandpath line 45.
BEGIN failed--compilation aborted at /media/guillermo/Work/miniconda3/envs/islandpath/bin/islandpath line 45.
`
Can someone help me?
Thanks

**Comment by innovate-invent** [comment]
Hi and thank you for your interest in islandpath. I recommend you run islandpath via the docker container:
```
docker run --rm -v$PWD:$PWD quay.io/biocontainers/islandpath:1.0.6--hdfd78af_0 islandpath
```
