### ISSUE TITLE
Handling of genes across sequence start

### ISSUE THREAD

**Issue by cbertell** [brinkmanlab/islandpath#3]
User report of the problem:

When I use NC_002754.1.gbk, there is an exception like this:

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: start [2991448] is greater than end [252]. 
If you want to truncated and reverse complement, 
you must call trunc followed by revcom. Sorry.
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/share/perl5/Bio/Root/Root.pm:449
STACK: Bio::PrimarySeqI::trunc /usr/share/perl5/Bio/PrimarySeqI.pm:456
STACK: GenomeUtils::read_and_convert /home/haidong/下载/islandpath_dimob_v1.0.0/lib/GenomeUtils.pm:422
STACK: ./Dimob.pl:130

**Comment by HaidYi** [comment]
Thank you. After I remove the fisrt part of the position. It now can work well.

**Comment by innovate-invent** [comment]
A fix was made to islandpath to discard the offending gene.
brinkmanlab/islandpath@7aa93b9
This has been resolved for now.
